services:
  weave-socket:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: weave-socket
    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: "3001"

    ports:
      - "3001:3001"
